[build]
  command = "npx expo export:web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# (Optional) correct MIME if you later host a custom manifest
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
