[build]
  command = "npm ci && npm run build:web"
  publish = "dist"

# SPA routing for Expo Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proper MIME for the PWA manifest
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
